exports = {
  "clear-day": atob("ExPBAP//Ue4ERACIgIkiCACAnyGH8Mn/IH/wD/4d/9w/+Af/An/Jh/DCfICACCJIgIiAERAA"),
  "partly-cloudy-day": atob(
    "ExPCAP//HOdR7gAAAAAAAAAAAAAgAAACAIAAAAIAAgAAAKqAAAAKqoAAFVqqAAFVWqoBVVVqqBVVVWqBVVVVagVVVVWoFVVVVoAVVVVQIBVVVCAAAAAAgAAAAAAAAAAAAAAAAAAAAA=="
  ),
  cloudy: atob("ExPBAP//HOcAAAAAAAAAAAAAD8AD/Af/wP/4P/+P//n//z//5//8f/+H/8AAAAAAAAAAAAAA"),
  wind: atob("ExPBAP////8AAAAAAAPAAMgAAYAAMAf8QAA8AASAABA//AAAAAAAP/4AAGAADAAHAAAAAAAA"),
  fog: atob("ExPBAP////8AAAAAAAAAADAAH4A7/gAAAP74AAAD7+AAAA3/gAAAP34AAAD/8AAAAAAAAAAA"),
  rain: atob("ExPBAP//OWMAAAAAAAEAACAADgABwAB8AB/AB/wA/4Af8AP+AH/AB/AA/gAPgAAAAAAAAAAA"),
  snow: atob("ExPBAP////8AAAAAAAAAAAAACgAIiAMRgBJAAVAAHAAFQAEkAMRgCIgAKAAAAAAAAAAAAAAA"),
};
